name: ${name}
version: ${version}
main: me.xginko.betterworldstats.BetterWorldStats
authors: [ xGinko ]
softdepend: [ PlaceholderAPI ]
description: ${description}
website: ${url}
folia-supported: true
api-version: '1.13'